In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:

from google.colab import files
uploaded = files.upload()


Saving beginner.csv to beginner.csv


In [4]:
df = pd.read_csv("beginner.csv")

df = df.set_index("SERIAL")
df = df.sort_values(by = "INCWAGE", ascending = False)

#Clean data
df = df[(df.get("INCWAGE") != 99999999) & (df.get("INCWAGE").notnull())] 

In [6]:
#from sklearn import linear_model
import statsmodels.api as sm
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split


encoder = OneHotEncoder(drop='first', sparse=False, handle_unknown="ignore")

In [7]:
#Model 1
X_train, X_test, y_train, y_test = train_test_split(df[["YEAR", "EDUC", "SEX", "UHRSWORKT"]], df["INCWAGE"])

onehot_training = encoder.fit_transform(X_train)
print(onehot_training)
onehot_validation = encoder.transform(X_test)

model = LinearRegression()
model.fit(onehot_training, y_train)

print("Intercept ", model.intercept_)
print("Coeff ", model.coef_)
print("Mean squared error: %.2f" % np.mean((model.predict(onehot_validation) - y_test) ** 2))
print("MAE " + str(mean_absolute_error(model.predict(onehot_validation), y_test)))

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]
Intercept  10614.529610007128
Coeff  [-1.20750190e+02 -6.86757656e+02  1.15795806e+03 -1.09994357e+03
  7.27330400e+02  3.75065871e+02  1.15794146e+03  8.18848914e+02
  3.20560830e+03  4.06590505e+03  4.75822221e+03  7.82302946e+03
 -1.25724890e+03 -1.58427548e+03  8.27612538e+01  2.13200143e+02
 -9.35017536e+01 -4.24116661e+01  3.83435680e+02  3.19674632e+03
  4.77796340e+03  4.71203698e+03  9.34890985e+03  2.16181244e+04
  3.10928764e+04  7.27968065e+04  6.87854542e+04 -8.96607858e+03
 -8.06133599e+02 -2.08247793e+04 -1.80333383e+04 -7.79500190e+03
  5.91579563e+03 -1.26132349e+04 -8.06914021e+03 -5.11601743e+03
  1.03729566e+04 -9.03523426e+03 -2.10968543e+03 -6.31641965e+03
 -1.38137313e+04 -1.45801817e+03 -2.26945471e+03 -1.32387705e+03
  1.41381544e+04  4.78514388e+03 -1.19176495e+04 -1.49297839e+03
 -2.33509257e+03 -3.8426060

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [3] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


In [8]:
#Model 2
X2_train, X2_test, y_train2, y_test2 = train_test_split(df[["EMPSTAT", "WKSTAT", "NFAMS", "EDUC"]], df["INCWAGE"])

onehot_training2 = encoder.fit_transform(X2_train)
onehot_validation2 = encoder.transform(X2_test)

model2 = LinearRegression()
model2.fit(onehot_training2, y_train2)
print("Intercept ", model2.intercept_)
print("Coeff ", model2.coef_)
print("Mean squared error: %.2f" % np.mean((model2.predict(onehot_validation2) - y_test2) ** 2))
print("MAE " + str(mean_absolute_error(model2.predict(onehot_validation2), y_test2)))

Intercept  -1.5512059282475197e+17
Coeff  [ 1.55120593e+17  1.37850960e+17  8.09753935e+16  8.09753935e+16
 -4.75597106e+04 -4.68796172e+04 -5.18974061e+04 -1.93108133e+03
  1.72696329e+16 -1.36377709e+04 -2.21405542e+04 -1.14194871e+04
 -3.19311816e+04 -3.40132442e+04  1.72696329e+16  7.41451993e+16
  7.41451993e+16  1.55120593e+17 -7.85853598e+03 -1.11813886e+04
 -1.02649142e+04 -4.18618507e+03  1.66986818e+03 -1.17101755e+04
 -4.03346439e+03 -1.61493932e+03 -3.03264904e+04 -8.99125506e+02
 -5.82659713e+03 -4.60146466e+03 -2.93750921e+03 -3.64613091e+03
 -3.78048619e+03 -4.59900000e+03 -1.68150000e+03 -1.09800000e+03
  9.20000000e+01  5.11500000e+02  5.27800000e+03  1.77000000e+04
  3.01040000e+04  6.67440000e+04  6.16810000e+04]
Mean squared error: 1835191090.78
MAE 19679.34797226308


In [9]:
#Model 3
X3_train, X3_test, y_train3, y_test3 = train_test_split(df[["RACE", "EMPSTAT"]], df["INCWAGE"])

onehot_training3 = encoder.fit_transform(X3_train)
onehot_validation3 = encoder.transform(X3_test)


model3 = LinearRegression()
model3.fit(onehot_training3, y_train3)
print("Intercept ", model3.intercept_)
print("Coeff ", model3.coef_)

print("Mean squared error: %.2f" % np.mean((model3.predict(onehot_validation3) - y_test3) ** 2))
print("MAE " + str(mean_absolute_error(model3.predict(onehot_validation3), y_test3)))

Intercept  58330.09445954311
Coeff  [ -5253.046273    -8663.82323768   6211.7547669   -7344.8281
  -6110.0632191   -4460.11572147   -441.90651906 -10788.40378024
 -11306.2719197    4926.57090482    534.80628544  -9704.04540363
 -43270.81361782  -5810.62958791 -23270.81361781 -11059.28084173
 -21198.99201365 -41678.054836   -56852.73934987 -55536.40775105
 -55792.66041536 -55898.55080405]
Mean squared error: 1549309316.89
MAE 21268.281629834273


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


In [10]:
#Model 4
X4_train, X4_test, y_train4, y_test4 = train_test_split(df[["YEAR", "EDUC", "SEX", "UHRSWORKT", "EMPSTAT", "WKSTAT", "NFAMS", "RACE"]], df["INCWAGE"])

onehot_training4 = encoder.fit_transform(X4_train)
onehot_validation4 = encoder.transform(X4_test)

model4 = LinearRegression()
model4.fit(onehot_training4, y_train4)
print("Intercept ", model4.intercept_)
print("Coeff ", model4.coef_)
print("Mean squared error: %.2f" % np.mean((model4.predict(onehot_validation4) - y_test4) ** 2))
print("MAE " + str(mean_absolute_error(model4.predict(onehot_validation4), y_test4)))


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [3, 7] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


Intercept  1.4956076473345252e+16
Coeff  [ 1.26843328e+02 -1.99925055e+03 -2.11479180e+02 -1.43164506e+03
 -7.99915610e+01  6.16198552e+02  1.81407528e+03  7.69211194e+02
  3.54029264e+03  4.71294339e+03  6.21505508e+03  7.44923471e+03
 -3.87772112e+03 -3.29706356e+03 -1.39176857e+03 -2.10311071e+03
 -1.77015225e+03 -2.14713499e+03  3.54277056e+02  7.85321275e+02
  2.51574088e+03  2.81821801e+03  7.54972088e+03  1.90439232e+04
  3.04296577e+04  6.22704685e+04  5.26004035e+04 -7.47553997e+03
  4.70125711e+04 -1.66788925e+03 -1.75136349e+04 -1.02837757e+04
 -9.83367935e+03 -1.55423613e+04 -1.62853788e+04 -5.86485076e+03
 -1.60882931e+04 -1.28934706e+04 -8.72476725e+03 -1.00915596e+04
 -1.99043939e+04 -6.92153901e+03 -1.05858428e+04 -7.88838430e+03
  5.40427579e+03 -1.83717283e+03 -1.39103745e+04 -6.50099038e+03
 -1.21623225e+04 -5.50475367e+03 -6.10451934e+03  9.59334651e+02
 -1.71024078e+03 -3.59587915e+03  1.23998344e+04 -6.64851574e+02
 -9.87696933e+03 -1.59046257e+03 -5.80378823e+03 