In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:

from google.colab import files
uploaded = files.upload()


Saving beginner.csv to beginner.csv


In [4]:
df = pd.read_csv("beginner.csv")

df = df.set_index("SERIAL")
df = df.sort_values(by = "INCWAGE", ascending = False)

#Clean data
df = df[(df.get("INCWAGE") != 99999999) & (df.get("INCWAGE").notnull())] 

In [5]:
#from sklearn import linear_model
import statsmodels.api as sm
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split


encoder = OneHotEncoder(drop='first', sparse=False, handle_unknown="ignore")


#Model 1
X_train, X_test, y_train, y_test = train_test_split(df[["YEAR", "EDUC", "SEX", "UHRSWORKT"]], df["INCWAGE"])

onehot_training = encoder.fit_transform(X_train)
print(onehot_training)
onehot_validation = encoder.transform(X_test)

model = LinearRegression()
model.fit(onehot_training, y_train)

print("Intercept ", model.intercept_)
print("Coeff ", model.coef_)
print("Mean squared error: %.2f" % np.mean((model.predict(onehot_validation) - y_test) ** 2))
print("MAE " + str(mean_absolute_error(model.predict(onehot_validation), y_test)))


#Model 2
X2_train, X2_test, y_train2, y_test2 = train_test_split(df[["EMPSTAT", "WKSTAT", "NFAMS", "EDUC"]], df["INCWAGE"])

onehot_training2 = encoder.fit_transform(X2_train)
onehot_validation2 = encoder.transform(X2_test)

model2 = LinearRegression()
model2.fit(onehot_training2, y_train2)
print("Intercept ", model2.intercept_)
print("Coeff ", model2.coef_)
print("Mean squared error: %.2f" % np.mean((model2.predict(onehot_validation2) - y_test2) ** 2))
print("MAE " + str(mean_absolute_error(model2.predict(onehot_validation2), y_test2)))


#Model 3
X3_train, X3_test, y_train3, y_test3 = train_test_split(df[["RACE", "EMPSTAT"]], df["INCWAGE"])

onehot_training3 = encoder.fit_transform(X3_train)
onehot_validation3 = encoder.transform(X3_test)


model3 = LinearRegression()
model3.fit(onehot_training3, y_train3)
print("Intercept ", model3.intercept_)
print("Coeff ", model3.coef_)

print("Mean squared error: %.2f" % np.mean((model3.predict(onehot_validation3) - y_test3) ** 2))
print("MAE " + str(mean_absolute_error(model3.predict(onehot_validation3), y_test3)))


#Model 4
X4_train, X4_test, y_train4, y_test4 = train_test_split(df[["YEAR", "EDUC", "SEX", "UHRSWORKT", "EMPSTAT", "WKSTAT", "NFAMS", "RACE"]], df["INCWAGE"])

onehot_training4 = encoder.fit_transform(X4_train)
onehot_validation4 = encoder.transform(X4_test)

model4 = LinearRegression()
model4.fit(onehot_training4, y_train4)
print("Intercept ", model4.intercept_)
print("Coeff ", model4.coef_)
print("Mean squared error: %.2f" % np.mean((model4.predict(onehot_validation4) - y_test4) ** 2))
print("MAE " + str(mean_absolute_error(model4.predict(onehot_validation4), y_test4)))







/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [3] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


Intercept  -12122.689755561929
Coeff  [ -1359.27400774  -3342.15557359  -1101.5968441   -2691.0391338
  -2175.37284835   -630.3592058   -1260.41837984  -1287.4245191
  -1388.6753709    2280.23221454   3236.63296761   4818.67391276
    694.10504239   -153.45059195   2084.53237015   2147.74816638
   1872.0402753    2386.06132885   2322.18989117   4505.56424517
   6748.12972636   7321.91946752  10975.94462064  24259.48584328
  35375.18119552  74181.33072455  59287.91496796  -8174.03680797
  71778.34970725    355.64693371   7513.40416229  14986.43613107
  19441.47672872  11736.4201985   12521.24670594  24561.12563116
  23981.53796981  12303.00278003  18241.16376862  16979.66870124
  10130.89277755  22743.43977353  21346.16088762  22329.50748576
  34270.93108509  26812.71434393  12113.27089982  19916.83191616
  26256.31757936  20085.83547473  22166.41420425  27201.9417161
  24620.07635078  20548.20132811  40028.74002337  21794.48533256
  18051.38117304  27424.32507919  29882.49338217  32583

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


MAE 19199.106114729984
Intercept  58780.574825713105
Coeff  [ -3907.54779049  -8104.1642259    5114.75147802  -7650.7659163
  -8639.17002808  -5479.81422515  -3045.27297139 -10036.77544255
  -8969.61679541  -4738.88426904    625.43581227 -11203.3149381
 -21878.27761588 -20878.27761588  -6553.6139116  -22878.27761588
 -11902.29720984 -19412.80326392 -39936.50344941 -56996.31669076
 -56348.79818679 -56185.6643576  -56696.78077319]
Mean squared error: 2247182741.05
MAE 21561.065024915446


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_encoders.py:174: UserWarning: Found unknown categories in columns [3, 7] during transform. These unknown categories will be encoded as all zeros
  UserWarning,


Intercept  2.050378959121452e+16
Coeff  [-4.94131022e+02 -2.50818399e+03 -3.88200069e+02 -6.87338893e+02
  5.06773281e+02  2.22944817e+02 -1.50143952e+03 -2.01014859e+02
  3.70757510e+03  5.28185149e+03  3.23595533e+03  8.38372551e+03
 -2.07217701e+03 -3.18854060e+03 -2.08290068e+03 -2.78953872e+03
 -2.59496560e+03 -2.46043713e+03  9.66930815e+02  7.35665908e+02
  2.07782239e+03  2.53213600e+03  6.54444621e+03  1.87049493e+04
  2.99579811e+04  6.80731760e+04  5.63892320e+04 -7.46884951e+03
  7.06351950e+04 -5.86806662e+03 -1.79646157e+04 -1.22003419e+04
  3.27837144e+02 -1.32942354e+04 -1.72655270e+04 -3.04001067e+03
  4.83644300e+02 -1.09393131e+04 -7.60614762e+03 -8.78591616e+03
 -1.51774282e+04 -2.39292333e+03 -4.94673680e+03 -3.88655728e+03
  8.63576362e+03 -5.84669488e+01 -1.68007062e+04 -4.83114472e+03
 -9.17639956e+02 -4.41989413e+03 -6.53958334e+02  1.27795334e+03
  7.91057506e+01 -3.51434368e+03  1.74066354e+04 -3.12470064e+03
 -3.31201080e+03  1.44322282e+03 -4.89529485e+03  